# Form implementation generated from reading ui file 'ui/ui_mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1575, 896)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/* ============================================================\n"
"   GLOBAL\n"
"   ============================================================ */\n"
"QWidget {\n"
"    background-color: #FAFAFA;\n"
"    color: #333333;\n"
"    font-family: \'Segoe UI\';\n"
"}\n"
"\n"
"QMainWindow {\n"
"    background-color: #FAFAFA;\n"
"    color: #333333;\n"
"}\n"
"\n"
"\n"
"/* ============================================================\n"
"   BOUTONS\n"
"   ============================================================ */\n"
"QPushButton {\n"
"    background-color: #F5F5F5;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 0px;\n"
"    padding: 4px 8px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-weight: normal;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QPushButton:hover    { background-color: #C96868; border-color: #B55555; color: #FFFFFF; }\n"
"QPushButton:pressed  { background-color: #7EACB5; border-color: #5E9CA5; color: #FFFFFF; }\n"
"QPushButton:disabled { background-color: #F8F8F8; border-color: #E0E0E0; color: #999999; }\n"
"\n"
"\n"
"/* ============================================================\n"
"   CHAMPS DE SAISIE\n"
"   ============================================================ */\n"
"QLineEdit,\n"
"QTextEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QDateTimeEdit,\n"
"QDateEdit,\n"
"QTimeEdit {\n"
"    background-color: #FFFFFF;\n"
"    color: #333333;\n"
"    border: 1px solid #E0E0E0;\n"
"    border-radius: 0px;\n"
"    padding: 4px;    \n"
"    font-family: \'Segoe UI\';\n"
"    selection-background-color: #E0E0E0;\n"
"    selection-color: #333333;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QTextEdit:focus,\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus,\n"
"QDateTimeEdit:focus,\n"
"QDateEdit:focus,\n"
"QTimeEdit:focus {\n"
"    border-color: #C0C0C0;\n"
"}\n"
"\n"
"/* Boutons up/down des SpinBox et DateTimeEdit */\n"
"QSpinBox::up-button,\n"
"QSpinBox::down-button,\n"
"QDoubleSpinBox::up-button,\n"
"QDoubleSpinBox::down-button,\n"
"QDateTimeEdit::up-button,\n"
"QDateTimeEdit::down-button,\n"
"QDateEdit::up-button,\n"
"QDateEdit::down-button,\n"
"QTimeEdit::up-button,\n"
"QTimeEdit::down-button {\n"
"    background-color: #F5F5F5;\n"
"    border: none;\n"
"    border-left: 1px solid #E0E0E0;\n"
"    border-radius: 0px;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover,\n"
"QDoubleSpinBox::up-button:hover,\n"
"QDoubleSpinBox::down-button:hover,\n"
"QDateTimeEdit::up-button:hover,\n"
"QDateTimeEdit::down-button:hover,\n"
"QDateEdit::up-button:hover,\n"
"QDateEdit::down-button:hover,\n"
"QTimeEdit::up-button:hover,\n"
"QTimeEdit::down-button:hover {\n"
"    background-color: #C96868;\n"
"}\n"
"\n"
"\n"
"/* ============================================================\n"
"   GROUPBOX\n"
"   ============================================================ */\n"
"QGroupBox {\n"
"    background-color: #FAFAFA;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 0px;\n"
"    margin-top: 8px;\n"
"    padding-top: 8px;\n"
"    font-family: \'Segoe UI\';\n"
"    color: #333333;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0 4px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"\n"
"/* ============================================================\n"
"   MENU BAR & MENUS\n"
"   ============================================================ */\n"
"QMenuBar {\n"
"    background-color: #F5F5F5;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 0px;\n"
"    font-family: \'Segoe UI\';\n"
"    font-weight: normal;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QMenuBar::item                 { background-color: transparent; color: #333333; padding: 4px 8px; }\n"
"QMenuBar::item:selected    { background-color: #C96868; color: #FFFFFF; }\n"
"QMenuBar::item:pressed     { background-color: #7EACB5; color: #FFFFFF; }\n"
"\n"
"QMenu {\n"
"    background-color: #FFFFFF;\n"
"    color: #333333;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QMenu::item              { padding: 4px 20px; }\n"
"QMenu::item:selected     { background-color: #C96868; color: #FFFFFF; }\n"
"QMenu::item:pressed      { background-color: #7EACB5; color: #FFFFFF; }\n"
"\n"
"\n"
"/* ============================================================\n"
"   SCROLLBARS\n"
"   ============================================================ */\n"
"QScrollBar:vertical {\n"
"    background-color: #F5F5F5;\n"
"    width: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #E0E0E0;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 0px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover { background-color: #D0D0D0; }\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: #F5F5F5;\n"
"    height: 12px;\n"
"    margin: 1px;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #E0E0E0;\n"
"    border: 1px solid #D0D0D0;\n"
"    border-radius: 0px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover { background-color: #D0D0D0; }\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_load_data = QtWidgets.QWidget()
        self.page_load_data.setObjectName("page_load_data")
        self.verticalLayout_home = QtWidgets.QVBoxLayout(self.page_load_data)
        self.verticalLayout_home.setObjectName("verticalLayout_home")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.page_load_data)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.lineEdit_lon2 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lon2.setObjectName("lineEdit_lon2")
        self.horizontalLayout_7.addWidget(self.lineEdit_lon2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 4, 1, 1)
        self.label_ref_folder = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_ref_folder.setObjectName("label_ref_folder")
        self.gridLayout.addWidget(self.label_ref_folder, 1, 0, 1, 1)
        self.label_raw_ref = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_raw_ref.setObjectName("label_raw_ref")
        self.gridLayout.addWidget(self.label_raw_ref, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.lineEdit_lon3 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lon3.setObjectName("lineEdit_lon3")
        self.horizontalLayout_11.addWidget(self.lineEdit_lon3)
        self.gridLayout.addLayout(self.horizontalLayout_11, 2, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.lineEdit_lon4 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lon4.setObjectName("lineEdit_lon4")
        self.horizontalLayout_12.addWidget(self.lineEdit_lon4)
        self.gridLayout.addLayout(self.horizontalLayout_12, 3, 4, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_lat2 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lat2.setObjectName("lineEdit_lat2")
        self.horizontalLayout_4.addWidget(self.lineEdit_lat2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 3, 1, 1)
        self.label_model_param_file_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_model_param_file_2.setObjectName("label_model_param_file_2")
        self.gridLayout.addWidget(self.label_model_param_file_2, 2, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_file3 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_file3.setObjectName("lineEdit_file3")
        self.horizontalLayout_9.addWidget(self.lineEdit_file3)
        self.pushButton_browse_file3 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_browse_file3.setObjectName("pushButton_browse_file3")
        self.horizontalLayout_9.addWidget(self.pushButton_browse_file3)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_file4 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_file4.setObjectName("lineEdit_file4")
        self.horizontalLayout_10.addWidget(self.lineEdit_file4)
        self.pushButton_browse_file4 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_browse_file4.setObjectName("pushButton_browse_file4")
        self.horizontalLayout_10.addWidget(self.pushButton_browse_file4)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 1, 1, 1)
        self.pushButton_read_treat_data = QtWidgets.QPushButton(parent=self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_read_treat_data.sizePolicy().hasHeightForWidth())
        self.pushButton_read_treat_data.setSizePolicy(sizePolicy)
        self.pushButton_read_treat_data.setCheckable(False)
        self.pushButton_read_treat_data.setFlat(False)
        self.pushButton_read_treat_data.setObjectName("pushButton_read_treat_data")
        self.gridLayout.addWidget(self.pushButton_read_treat_data, 4, 0, 1, 5)
        self.label_model_param_file_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_model_param_file_3.setObjectName("label_model_param_file_3")
        self.gridLayout.addWidget(self.label_model_param_file_3, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_lon1 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lon1.setObjectName("lineEdit_lon1")
        self.horizontalLayout_8.addWidget(self.lineEdit_lon1)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 4, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_lat4 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lat4.setObjectName("lineEdit_lat4")
        self.horizontalLayout_6.addWidget(self.lineEdit_lat4)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 3, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 4, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_file2 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_file2.setObjectName("lineEdit_file2")
        self.horizontalLayout_2.addWidget(self.lineEdit_file2)
        self.pushButton_browse_file2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_browse_file2.setObjectName("pushButton_browse_file2")
        self.horizontalLayout_2.addWidget(self.pushButton_browse_file2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_lat3 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lat3.setObjectName("lineEdit_lat3")
        self.horizontalLayout_5.addWidget(self.lineEdit_lat3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 3, 1, 1)
        self.horizontalLayout_root = QtWidgets.QHBoxLayout()
        self.horizontalLayout_root.setObjectName("horizontalLayout_root")
        self.lineEdit_file1 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_file1.setObjectName("lineEdit_file1")
        self.horizontalLayout_root.addWidget(self.lineEdit_file1)
        self.pushButton_browse_file1 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_browse_file1.setObjectName("pushButton_browse_file1")
        self.horizontalLayout_root.addWidget(self.pushButton_browse_file1)
        self.gridLayout.addLayout(self.horizontalLayout_root, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_lat1 = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_lat1.setObjectName("lineEdit_lat1")
        self.horizontalLayout_3.addWidget(self.lineEdit_lat1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 3, 1, 1)
        self.verticalLayout_home.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page_load_data)
        self.page_coords = QtWidgets.QWidget()
        self.page_coords.setObjectName("page_coords")
        self.verticalLayout_coords_page = QtWidgets.QVBoxLayout(self.page_coords)
        self.verticalLayout_coords_page.setObjectName("verticalLayout_coords_page")
        self.groupBox_coordinates = QtWidgets.QGroupBox(parent=self.page_coords)
        self.groupBox_coordinates.setObjectName("groupBox_coordinates")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_coordinates)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_coords_plot = QtWidgets.QPushButton(parent=self.groupBox_coordinates)
        self.pushButton_coords_plot.setObjectName("pushButton_coords_plot")
        self.verticalLayout_2.addWidget(self.pushButton_coords_plot)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_coords_page.addWidget(self.groupBox_coordinates)
        self.stackedWidget.addWidget(self.page_coords)
        self.page_CTD_profiles = QtWidgets.QWidget()
        self.page_CTD_profiles.setObjectName("page_CTD_profiles")
        self.verticalLayout_profiles_page = QtWidgets.QVBoxLayout(self.page_CTD_profiles)
        self.verticalLayout_profiles_page.setObjectName("verticalLayout_profiles_page")
        self.groupBox_sensor_config = QtWidgets.QGroupBox(parent=self.page_CTD_profiles)
        self.groupBox_sensor_config.setObjectName("groupBox_sensor_config")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_sensor_config)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=self.groupBox_sensor_config)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_9 = QtWidgets.QLabel(parent=self.splitter)
        self.label_9.setObjectName("label_9")
        self.comboBox_CTD = QtWidgets.QComboBox(parent=self.splitter)
        self.comboBox_CTD.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_CTD.setObjectName("comboBox_CTD")
        self.comboBox_CTD.addItem("")
        self.comboBox_CTD.addItem("")
        self.comboBox_CTD.addItem("")
        self.verticalLayout_3.addWidget(self.splitter)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_sensor_config)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.checkBox_avg_CTD_vals = QtWidgets.QCheckBox(parent=self.groupBox_sensor_config)
        self.checkBox_avg_CTD_vals.setText("")
        self.checkBox_avg_CTD_vals.setObjectName("checkBox_avg_CTD_vals")
        self.horizontalLayout_16.addWidget(self.checkBox_avg_CTD_vals)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.pushButton_CTD_plot = QtWidgets.QPushButton(parent=self.groupBox_sensor_config)
        self.pushButton_CTD_plot.setObjectName("pushButton_CTD_plot")
        self.verticalLayout_3.addWidget(self.pushButton_CTD_plot)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_profiles_page.addWidget(self.groupBox_sensor_config)
        self.stackedWidget.addWidget(self.page_CTD_profiles)
        self.page_speed_profiles = QtWidgets.QWidget()
        self.page_speed_profiles.setObjectName("page_speed_profiles")
        self.verticalLayout_velocity_page = QtWidgets.QVBoxLayout(self.page_speed_profiles)
        self.verticalLayout_velocity_page.setObjectName("verticalLayout_velocity_page")
        self.groupBox_model_config = QtWidgets.QGroupBox(parent=self.page_speed_profiles)
        self.groupBox_model_config.setObjectName("groupBox_model_config")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_model_config)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_model_config)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.lineEdit_no_motion_level = QtWidgets.QLineEdit(parent=self.groupBox_model_config)
        self.lineEdit_no_motion_level.setObjectName("lineEdit_no_motion_level")
        self.horizontalLayout_13.addWidget(self.lineEdit_no_motion_level)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_model_config)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.checkBox_avg_T_vals = QtWidgets.QCheckBox(parent=self.groupBox_model_config)
        self.checkBox_avg_T_vals.setText("")
        self.checkBox_avg_T_vals.setObjectName("checkBox_avg_T_vals")
        self.horizontalLayout_15.addWidget(self.checkBox_avg_T_vals)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        self.gridLayout_2.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_model_config)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.comboBox_method_to_plot = QtWidgets.QComboBox(parent=self.groupBox_model_config)
        self.comboBox_method_to_plot.setObjectName("comboBox_method_to_plot")
        self.comboBox_method_to_plot.addItem("")
        self.comboBox_method_to_plot.addItem("")
        self.comboBox_method_to_plot.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_method_to_plot)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.pushButton_speed_plot = QtWidgets.QPushButton(parent=self.groupBox_model_config)
        self.pushButton_speed_plot.setObjectName("pushButton_speed_plot")
        self.gridLayout_2.addWidget(self.pushButton_speed_plot, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 4, 0, 1, 1)
        self.verticalLayout_velocity_page.addWidget(self.groupBox_model_config)
        self.stackedWidget.addWidget(self.page_speed_profiles)
        self.page_hodograph = QtWidgets.QWidget()
        self.page_hodograph.setObjectName("page_hodograph")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_hodograph)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_model_config_2 = QtWidgets.QGroupBox(parent=self.page_hodograph)
        self.groupBox_model_config_2.setObjectName("groupBox_model_config_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_model_config_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_model_config_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.lineEdit_no_motion_level_2 = QtWidgets.QLineEdit(parent=self.groupBox_model_config_2)
        self.lineEdit_no_motion_level_2.setObjectName("lineEdit_no_motion_level_2")
        self.horizontalLayout_17.addWidget(self.lineEdit_no_motion_level_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_model_config_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.spinBox_resolution = QtWidgets.QSpinBox(parent=self.groupBox_model_config_2)
        self.spinBox_resolution.setMinimumSize(QtCore.QSize(0, 24))
        self.spinBox_resolution.setMinimum(1)
        self.spinBox_resolution.setMaximum(50)
        self.spinBox_resolution.setProperty("value", 5)
        self.spinBox_resolution.setObjectName("spinBox_resolution")
        self.horizontalLayout_14.addWidget(self.spinBox_resolution)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox_model_config_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.comboBox_hodograph_from = QtWidgets.QComboBox(parent=self.groupBox_model_config_2)
        self.comboBox_hodograph_from.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_hodograph_from.setObjectName("comboBox_hodograph_from")
        self.comboBox_hodograph_from.addItem("")
        self.comboBox_hodograph_from.addItem("")
        self.horizontalLayout_18.addWidget(self.comboBox_hodograph_from)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.pushButton_hodograph = QtWidgets.QPushButton(parent=self.groupBox_model_config_2)
        self.pushButton_hodograph.setObjectName("pushButton_hodograph")
        self.verticalLayout_5.addWidget(self.pushButton_hodograph)
        spacerItem6 = QtWidgets.QSpacerItem(20, 260, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.gridLayout_3.addWidget(self.groupBox_model_config_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_hodograph)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit_console = QtWidgets.QTextEdit(parent=self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.textEdit_console.setFont(font)
        self.textEdit_console.setReadOnly(True)
        self.textEdit_console.setObjectName("textEdit_console")
        self.gridLayout_4.addWidget(self.textEdit_console, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox_console = QtWidgets.QGroupBox(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox_console.sizePolicy().hasHeightForWidth())
        self.groupBox_console.setSizePolicy(sizePolicy)
        self.groupBox_console.setObjectName("groupBox_console")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_console)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.graph_layout = QtWidgets.QWidget(parent=self.groupBox_console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.graph_layout.sizePolicy().hasHeightForWidth())
        self.graph_layout.setSizePolicy(sizePolicy)
        self.graph_layout.setMinimumSize(QtCore.QSize(500, 500))
        self.graph_layout.setObjectName("graph_layout")
        self.gridLayout_9.addWidget(self.graph_layout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_console)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1575, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad = QtGui.QAction(parent=MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClean = QtGui.QAction(parent=MainWindow)
        self.actionClean.setObjectName("actionClean")
        self.actionLoad_Data = QtGui.QAction(parent=MainWindow)
        self.actionLoad_Data.setObjectName("actionLoad_Data")
        self.actionCoordinates = QtGui.QAction(parent=MainWindow)
        self.actionCoordinates.setObjectName("actionCoordinates")
        self.actionCTD_profiles = QtGui.QAction(parent=MainWindow)
        self.actionCTD_profiles.setObjectName("actionCTD_profiles")
        self.actionSpeed_Profiles = QtGui.QAction(parent=MainWindow)
        self.actionSpeed_Profiles.setObjectName("actionSpeed_Profiles")
        self.actionHodograph = QtGui.QAction(parent=MainWindow)
        self.actionHodograph.setObjectName("actionHodograph")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClean)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionLoad_Data)
        self.toolBar.addAction(self.actionCoordinates)
        self.toolBar.addAction(self.actionCTD_profiles)
        self.toolBar.addAction(self.actionSpeed_Profiles)
        self.toolBar.addAction(self.actionHodograph)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GEOVEL"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Load files"))
        self.label_5.setText(_translate("MainWindow", "Lon 2 (°)"))
        self.label_ref_folder.setText(_translate("MainWindow", "Sea-Bird file 2"))
        self.label_raw_ref.setText(_translate("MainWindow", "Sea-Bird file 1"))
        self.label_7.setText(_translate("MainWindow", "Lon 3 (°)"))
        self.label_8.setText(_translate("MainWindow", "Lon 4 (°)"))
        self.label_2.setText(_translate("MainWindow", "Lat 2 (°)"))
        self.label_model_param_file_2.setText(_translate("MainWindow", "Sea-Bird file 3"))
        self.pushButton_browse_file3.setText(_translate("MainWindow", "Browse"))
        self.pushButton_browse_file4.setText(_translate("MainWindow", "Browse"))
        self.pushButton_read_treat_data.setText(_translate("MainWindow", "Load and treat data"))
        self.label_model_param_file_3.setText(_translate("MainWindow", "Sea-Bird file 4"))
        self.label_6.setText(_translate("MainWindow", "Lon 1 (°)"))
        self.label_4.setText(_translate("MainWindow", "Lat 4 (°)"))
        self.pushButton_browse_file2.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "Lat 3 (°)"))
        self.pushButton_browse_file1.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "Lat 1 (°)"))
        self.groupBox_coordinates.setTitle(_translate("MainWindow", "Coordinates Page"))
        self.pushButton_coords_plot.setText(_translate("MainWindow", "Create localization plot"))
        self.groupBox_sensor_config.setTitle(_translate("MainWindow", "CTD Profiles Page"))
        self.label_9.setText(_translate("MainWindow", "Plotting variable"))
        self.comboBox_CTD.setItemText(0, _translate("MainWindow", "Temperature (°C)"))
        self.comboBox_CTD.setItemText(1, _translate("MainWindow", "Salinity (PSU)"))
        self.comboBox_CTD.setItemText(2, _translate("MainWindow", "Density (kg m⁻³)"))
        self.label_13.setText(_translate("MainWindow", "Average CTD values"))
        self.pushButton_CTD_plot.setText(_translate("MainWindow", "Create profile plot"))
        self.groupBox_model_config.setTitle(_translate("MainWindow", "GEOVEL Profiles Page"))
        self.label_10.setText(_translate("MainWindow", "Level of no motion (m)"))
        self.label_12.setText(_translate("MainWindow", "Average triangle values"))
        self.label_17.setText(_translate("MainWindow", "GEOVEL calculation to plot"))
        self.comboBox_method_to_plot.setItemText(0, _translate("MainWindow", "Isobaric method"))
        self.comboBox_method_to_plot.setItemText(1, _translate("MainWindow", "Isopycnal method"))
        self.comboBox_method_to_plot.setItemText(2, _translate("MainWindow", "Both"))
        self.pushButton_speed_plot.setText(_translate("MainWindow", "Create speed plot"))
        self.groupBox_model_config_2.setTitle(_translate("MainWindow", "Hodograph Page"))
        self.label_14.setText(_translate("MainWindow", "Level of no motion (m)"))
        self.label_11.setText(_translate("MainWindow", "Resolution (points per meter)"))
        self.label_15.setText(_translate("MainWindow", "GEOVEL calculation to plot"))
        self.comboBox_hodograph_from.setItemText(0, _translate("MainWindow", "Isobaric method"))
        self.comboBox_hodograph_from.setItemText(1, _translate("MainWindow", "Isopycnal method (Average)"))
        self.pushButton_hodograph.setText(_translate("MainWindow", "Create hodograph"))
        self.groupBox.setTitle(_translate("MainWindow", "Console Output"))
        self.groupBox_console.setTitle(_translate("MainWindow", "Graphical Output"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad.setText(_translate("MainWindow", "Open Config"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save Config"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionClean.setText(_translate("MainWindow", "Clean Fields"))
        self.actionLoad_Data.setText(_translate("MainWindow", "Load data"))
        self.actionCoordinates.setText(_translate("MainWindow", "Coordinates"))
        self.actionCTD_profiles.setText(_translate("MainWindow", "CTD Profiles"))
        self.actionSpeed_Profiles.setText(_translate("MainWindow", "GEOVEL Profiles"))
        self.actionHodograph.setText(_translate("MainWindow", "Hodograph"))
